Repository geoschem/GCHP, pull requests merged in 2024-03, with the labels that each got.

#392 Fix bug in advection when using raw GMAO meteorology files
  CHANGELOG.md
  src/GCHP_GridComp/GCHPctmEnv_GridComp/GCHPctmEnv_GridCompMod.F90
Labels: bugfix

#394 Now use short submodule names in .gitmodules
  .gitmodules
  CHANGELOG.md
Labels: no-diff-to-benchmark, bugfix

#396 Add GCHP_WRAPPER cpp definition
  CHANGELOG.md
  src/GCHP_GridComp/CMakeLists.txt
Labels: feature, build, no-diff-to-benchmark

#395 Expand GCHP advection diagnostics
  CHANGELOG.md
  src/GCHP_GridComp/GCHPctmEnv_GridComp/GCHPctmEnv_GridCompMod.F90
Labels: no-diff-to-benchmark, topic: Diagnostics
