Repository geoschem/GCHP, pull requests merged in 2024-12, with the labels that each got.

#463 Add KPP Standalone into GEOS-Chem 14.5.1
  CHANGELOG.md
  src/CMakeLists.txt
Labels: category: Feature Request, no-diff-to-benchmark

#456 Fix GCHPctmEnv small numerical bugs
  CHANGELOG.md
  src/GCHP_GridComp/GCHPctmEnv_GridComp/GCHPctmEnv_GridCompMod.F90
Labels: topic: Diagnostics, topic: Runtime, category: Bug Fix

#464 Fixed CMake error to prevent KPP standalone being built in carbon sim
  CHANGELOG.md
  src/CMakeLists.txt
Labels: topic: Build, category: Bug Fix
